### ISSUE TITLE
Proxy Usage

### ISSUE THREAD

**Issue by bluntk** [hansott/pinterest-php#41]
Hi, how can we use proxy for api requests?

**Comment by hansott** [comment]
Hi @bluntk, in order to help you better, you'll need to be a bit more detailed!

Do you want to send requests to pinterest over a proxy? You have two options:

* You can implement your own HTTP client (e.g. using Guzzle or copy the current `BuzzClient` in your codebase and set the proxy option) (https://github.com/hansott/pinterest-php/blob/master/src/Pinterest/Http/ClientInterface.php):
```php
class YourImplementation implements ClientInterface
{
  public function __construct(Client $guzzleClient)
  {
    // ...
  }

  public function execute(Request $request)
  {
    // use guzzle to send request
  }
}
```
* You can create a PR/fork to pass a `Curl` instance to the `BuzzClient`, in that way you can use `setProxy` on the `Curl` client:
```php
class BuzzClient implements ClientInterface
{
    public function __construct(Curl $curl = null) // Might be best to type-hint for the client interface of Buzz instead of the concrete class Curl
    {
        $this->client = new Browser($buzzClient !== null ? $buzzClient : new Curl()); // Backwards compatible
    }
}
```

**Comment by bluntk** [comment]
I am using this class for uploading images to pinterest but want to this with a proxy via cURL. I do not have that much experience with OOP. By the way your work is just perfect.

**Comment by hansott** [comment]
I don't have much time at this moment, if you can wait a few days I might be able to add the second option. Thanks for your kind words! 😊

**Comment by bluntk** [comment]
No problem hope soon i will be able to do staff like this. I will try to solve how to use proxy till you updated. Please let me know when it is done. Best wishes.

**Comment by hansott** [comment]
Released https://github.com/hansott/pinterest-php/releases/tag/3.2.3

Example:

```php
$curl = new Curl();
$curl->setProxy("your proxy"); // see https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html
$client = new Browser($curl);
$buzzClient = new BuzzClient($client);
$auth = new Pinterest\Authentication($buzzClient, ...);
```

**Comment by bluntk** [comment]
You are the best! Thank you
